# Generated by Django 2.0.3 on 2018-04-04 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compendium', '0006_auto_20180404_0244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='capstonepage',
            old_name='intro',
            new_name='student_name',
        ),
    ]
