# Generated by Django 2.0.3 on 2018-04-04 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compendium', '0007_auto_20180404_0253'),
    ]

    operations = [
        migrations.AddField(
            model_name='capstonepage',
            name='semester',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
