# Generated by Django 2.0.3 on 2018-04-04 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compendium', '0009_auto_20180404_0459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='capstonepage',
            old_name='student_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='capstonepage',
            name='date',
        ),
    ]
