# Generated by Django 2.0.3 on 2018-04-15 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0040_page_draft_title'),
        ('compendium', '0012_capstonepage_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compendiumindexpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='CompendiumIndexPage',
        ),
    ]
